// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet_sign.proto

package com.labs339.platform.sign;

public interface ExportPublicKeyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:labs339.wallet.sign.ExportPublicKeyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>repeated .labs339.wallet.sign.PublicKey public_key = 3;</code>
   */
  java.util.List<com.labs339.platform.sign.PublicKey> 
      getPublicKeyList();
  /**
   * <code>repeated .labs339.wallet.sign.PublicKey public_key = 3;</code>
   */
  com.labs339.platform.sign.PublicKey getPublicKey(int index);
  /**
   * <code>repeated .labs339.wallet.sign.PublicKey public_key = 3;</code>
   */
  int getPublicKeyCount();
  /**
   * <code>repeated .labs339.wallet.sign.PublicKey public_key = 3;</code>
   */
  java.util.List<? extends com.labs339.platform.sign.PublicKeyOrBuilder> 
      getPublicKeyOrBuilderList();
  /**
   * <code>repeated .labs339.wallet.sign.PublicKey public_key = 3;</code>
   */
  com.labs339.platform.sign.PublicKeyOrBuilder getPublicKeyOrBuilder(
      int index);
}
