// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet_sign.proto

package com.labs339.platform.sign;

public interface PublicKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:labs339.wallet.sign.PublicKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wallet = 1;</code>
   * @return The wallet.
   */
  java.lang.String getWallet();
  /**
   * <code>string wallet = 1;</code>
   * @return The bytes for wallet.
   */
  com.google.protobuf.ByteString
      getWalletBytes();

  /**
   * <code>string chain = 2;</code>
   * @return The chain.
   */
  java.lang.String getChain();
  /**
   * <code>string chain = 2;</code>
   * @return The bytes for chain.
   */
  com.google.protobuf.ByteString
      getChainBytes();

  /**
   * <code>string public_key_hex = 3;</code>
   * @return The publicKeyHex.
   */
  java.lang.String getPublicKeyHex();
  /**
   * <code>string public_key_hex = 3;</code>
   * @return The bytes for publicKeyHex.
   */
  com.google.protobuf.ByteString
      getPublicKeyHexBytes();

  /**
   * <code>uint64 index = 4;</code>
   * @return The index.
   */
  long getIndex();
}
