// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet_sign.proto

package com.labs339.platform.sign;

/**
 * Protobuf type {@code labs339.wallet.sign.SignTxMessageRequest}
 */
public final class SignTxMessageRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:labs339.wallet.sign.SignTxMessageRequest)
    SignTxMessageRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SignTxMessageRequest.newBuilder() to construct.
  private SignTxMessageRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SignTxMessageRequest() {
    wallet_ = "";
    chain_ = "";
    unSignMsg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SignTxMessageRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.labs339.platform.sign.WalletSignProto.internal_static_labs339_wallet_sign_SignTxMessageRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.labs339.platform.sign.WalletSignProto.internal_static_labs339_wallet_sign_SignTxMessageRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.labs339.platform.sign.SignTxMessageRequest.class, com.labs339.platform.sign.SignTxMessageRequest.Builder.class);
  }

  public static final int WALLET_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object wallet_ = "";
  /**
   * <code>string wallet = 1;</code>
   * @return The wallet.
   */
  @java.lang.Override
  public java.lang.String getWallet() {
    java.lang.Object ref = wallet_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wallet_ = s;
      return s;
    }
  }
  /**
   * <code>string wallet = 1;</code>
   * @return The bytes for wallet.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWalletBytes() {
    java.lang.Object ref = wallet_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wallet_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHAIN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object chain_ = "";
  /**
   * <code>string chain = 2;</code>
   * @return The chain.
   */
  @java.lang.Override
  public java.lang.String getChain() {
    java.lang.Object ref = chain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chain_ = s;
      return s;
    }
  }
  /**
   * <code>string chain = 2;</code>
   * @return The bytes for chain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChainBytes() {
    java.lang.Object ref = chain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDEX_FIELD_NUMBER = 3;
  private long index_ = 0L;
  /**
   * <code>uint64 index = 3;</code>
   * @return The index.
   */
  @java.lang.Override
  public long getIndex() {
    return index_;
  }

  public static final int UN_SIGN_MSG_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object unSignMsg_ = "";
  /**
   * <code>string un_sign_msg = 4;</code>
   * @return The unSignMsg.
   */
  @java.lang.Override
  public java.lang.String getUnSignMsg() {
    java.lang.Object ref = unSignMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      unSignMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string un_sign_msg = 4;</code>
   * @return The bytes for unSignMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnSignMsgBytes() {
    java.lang.Object ref = unSignMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      unSignMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(wallet_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, wallet_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chain_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, chain_);
    }
    if (index_ != 0L) {
      output.writeUInt64(3, index_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unSignMsg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, unSignMsg_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(wallet_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, wallet_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chain_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, chain_);
    }
    if (index_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, index_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(unSignMsg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, unSignMsg_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.labs339.platform.sign.SignTxMessageRequest)) {
      return super.equals(obj);
    }
    com.labs339.platform.sign.SignTxMessageRequest other = (com.labs339.platform.sign.SignTxMessageRequest) obj;

    if (!getWallet()
        .equals(other.getWallet())) return false;
    if (!getChain()
        .equals(other.getChain())) return false;
    if (getIndex()
        != other.getIndex()) return false;
    if (!getUnSignMsg()
        .equals(other.getUnSignMsg())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WALLET_FIELD_NUMBER;
    hash = (53 * hash) + getWallet().hashCode();
    hash = (37 * hash) + CHAIN_FIELD_NUMBER;
    hash = (53 * hash) + getChain().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIndex());
    hash = (37 * hash) + UN_SIGN_MSG_FIELD_NUMBER;
    hash = (53 * hash) + getUnSignMsg().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.labs339.platform.sign.SignTxMessageRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.labs339.platform.sign.SignTxMessageRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.labs339.platform.sign.SignTxMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.labs339.platform.sign.SignTxMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.labs339.platform.sign.SignTxMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.labs339.platform.sign.SignTxMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.labs339.platform.sign.SignTxMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.labs339.platform.sign.SignTxMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.labs339.platform.sign.SignTxMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.labs339.platform.sign.SignTxMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.labs339.platform.sign.SignTxMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.labs339.platform.sign.SignTxMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.labs339.platform.sign.SignTxMessageRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code labs339.wallet.sign.SignTxMessageRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:labs339.wallet.sign.SignTxMessageRequest)
      com.labs339.platform.sign.SignTxMessageRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.labs339.platform.sign.WalletSignProto.internal_static_labs339_wallet_sign_SignTxMessageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.labs339.platform.sign.WalletSignProto.internal_static_labs339_wallet_sign_SignTxMessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.labs339.platform.sign.SignTxMessageRequest.class, com.labs339.platform.sign.SignTxMessageRequest.Builder.class);
    }

    // Construct using com.labs339.platform.sign.SignTxMessageRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      wallet_ = "";
      chain_ = "";
      index_ = 0L;
      unSignMsg_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.labs339.platform.sign.WalletSignProto.internal_static_labs339_wallet_sign_SignTxMessageRequest_descriptor;
    }

    @java.lang.Override
    public com.labs339.platform.sign.SignTxMessageRequest getDefaultInstanceForType() {
      return com.labs339.platform.sign.SignTxMessageRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.labs339.platform.sign.SignTxMessageRequest build() {
      com.labs339.platform.sign.SignTxMessageRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.labs339.platform.sign.SignTxMessageRequest buildPartial() {
      com.labs339.platform.sign.SignTxMessageRequest result = new com.labs339.platform.sign.SignTxMessageRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.labs339.platform.sign.SignTxMessageRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.wallet_ = wallet_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.chain_ = chain_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.index_ = index_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.unSignMsg_ = unSignMsg_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.labs339.platform.sign.SignTxMessageRequest) {
        return mergeFrom((com.labs339.platform.sign.SignTxMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.labs339.platform.sign.SignTxMessageRequest other) {
      if (other == com.labs339.platform.sign.SignTxMessageRequest.getDefaultInstance()) return this;
      if (!other.getWallet().isEmpty()) {
        wallet_ = other.wallet_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getChain().isEmpty()) {
        chain_ = other.chain_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getIndex() != 0L) {
        setIndex(other.getIndex());
      }
      if (!other.getUnSignMsg().isEmpty()) {
        unSignMsg_ = other.unSignMsg_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              wallet_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              chain_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              index_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              unSignMsg_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object wallet_ = "";
    /**
     * <code>string wallet = 1;</code>
     * @return The wallet.
     */
    public java.lang.String getWallet() {
      java.lang.Object ref = wallet_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wallet_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string wallet = 1;</code>
     * @return The bytes for wallet.
     */
    public com.google.protobuf.ByteString
        getWalletBytes() {
      java.lang.Object ref = wallet_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wallet_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string wallet = 1;</code>
     * @param value The wallet to set.
     * @return This builder for chaining.
     */
    public Builder setWallet(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      wallet_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string wallet = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWallet() {
      wallet_ = getDefaultInstance().getWallet();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string wallet = 1;</code>
     * @param value The bytes for wallet to set.
     * @return This builder for chaining.
     */
    public Builder setWalletBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      wallet_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object chain_ = "";
    /**
     * <code>string chain = 2;</code>
     * @return The chain.
     */
    public java.lang.String getChain() {
      java.lang.Object ref = chain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chain = 2;</code>
     * @return The bytes for chain.
     */
    public com.google.protobuf.ByteString
        getChainBytes() {
      java.lang.Object ref = chain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chain = 2;</code>
     * @param value The chain to set.
     * @return This builder for chaining.
     */
    public Builder setChain(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      chain_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string chain = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChain() {
      chain_ = getDefaultInstance().getChain();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string chain = 2;</code>
     * @param value The bytes for chain to set.
     * @return This builder for chaining.
     */
    public Builder setChainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      chain_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long index_ ;
    /**
     * <code>uint64 index = 3;</code>
     * @return The index.
     */
    @java.lang.Override
    public long getIndex() {
      return index_;
    }
    /**
     * <code>uint64 index = 3;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(long value) {

      index_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 index = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      index_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object unSignMsg_ = "";
    /**
     * <code>string un_sign_msg = 4;</code>
     * @return The unSignMsg.
     */
    public java.lang.String getUnSignMsg() {
      java.lang.Object ref = unSignMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unSignMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string un_sign_msg = 4;</code>
     * @return The bytes for unSignMsg.
     */
    public com.google.protobuf.ByteString
        getUnSignMsgBytes() {
      java.lang.Object ref = unSignMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unSignMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string un_sign_msg = 4;</code>
     * @param value The unSignMsg to set.
     * @return This builder for chaining.
     */
    public Builder setUnSignMsg(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      unSignMsg_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string un_sign_msg = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnSignMsg() {
      unSignMsg_ = getDefaultInstance().getUnSignMsg();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string un_sign_msg = 4;</code>
     * @param value The bytes for unSignMsg to set.
     * @return This builder for chaining.
     */
    public Builder setUnSignMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      unSignMsg_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:labs339.wallet.sign.SignTxMessageRequest)
  }

  // @@protoc_insertion_point(class_scope:labs339.wallet.sign.SignTxMessageRequest)
  private static final com.labs339.platform.sign.SignTxMessageRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.labs339.platform.sign.SignTxMessageRequest();
  }

  public static com.labs339.platform.sign.SignTxMessageRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SignTxMessageRequest>
      PARSER = new com.google.protobuf.AbstractParser<SignTxMessageRequest>() {
    @java.lang.Override
    public SignTxMessageRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SignTxMessageRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SignTxMessageRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.labs339.platform.sign.SignTxMessageRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

