// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet_sign.proto

package com.labs339.platform.sign;

public interface SupportSignWayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:labs339.wallet.sign.SupportSignWayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string chain = 1;</code>
   * @return The chain.
   */
  java.lang.String getChain();
  /**
   * <code>string chain = 1;</code>
   * @return The bytes for chain.
   */
  com.google.protobuf.ByteString
      getChainBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
