// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet_sign.proto

package com.labs339.platform.sign;

public final class WalletSignProto {
  private WalletSignProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labs339_wallet_sign_SupportSignWayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labs339_wallet_sign_SupportSignWayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labs339_wallet_sign_SupportSignWayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labs339_wallet_sign_SupportSignWayResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labs339_wallet_sign_ExportPublicKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labs339_wallet_sign_ExportPublicKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labs339_wallet_sign_ExportPublicKeyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labs339_wallet_sign_ExportPublicKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labs339_wallet_sign_PublicKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labs339_wallet_sign_PublicKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labs339_wallet_sign_SignTxMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labs339_wallet_sign_SignTxMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_labs339_wallet_sign_SignTxMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_labs339_wallet_sign_SignTxMessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021wallet_sign.proto\022\023labs339.wallet.sign" +
      "\"4\n\025SupportSignWayRequest\022\r\n\005chain\030\001 \001(\t" +
      "\022\014\n\004type\030\002 \001(\t\"D\n\026SupportSignWayResponse" +
      "\022\014\n\004code\030\001 \001(\t\022\013\n\003msg\030\002 \001(\t\022\017\n\007support\030\003" +
      " \001(\010\"U\n\026ExportPublicKeyRequest\022\016\n\006wallet" +
      "\030\001 \001(\t\022\r\n\005chain\030\002 \001(\t\022\016\n\006cursor\030\003 \001(\004\022\014\n" +
      "\004size\030\004 \001(\004\"h\n\027ExportPublicKeyResponse\022\014" +
      "\n\004code\030\001 \001(\t\022\013\n\003msg\030\002 \001(\t\0222\n\npublic_key\030" +
      "\003 \003(\0132\036.labs339.wallet.sign.PublicKey\"Q\n" +
      "\tPublicKey\022\016\n\006wallet\030\001 \001(\t\022\r\n\005chain\030\002 \001(" +
      "\t\022\026\n\016public_key_hex\030\003 \001(\t\022\r\n\005index\030\004 \001(\004" +
      "\"Y\n\024SignTxMessageRequest\022\016\n\006wallet\030\001 \001(\t" +
      "\022\r\n\005chain\030\002 \001(\t\022\r\n\005index\030\003 \001(\004\022\023\n\013un_sig" +
      "n_msg\030\004 \001(\t\"E\n\025SignTxMessageResponse\022\014\n\004" +
      "code\030\001 \001(\t\022\013\n\003msg\030\002 \001(\t\022\021\n\tsignature\030\003 \001" +
      "(\t2\341\002\n\021WalletSignService\022n\n\021getSupportSi" +
      "gnWay\022*.labs339.wallet.sign.SupportSignW" +
      "ayRequest\032+.labs339.wallet.sign.SupportS" +
      "ignWayResponse\"\000\022r\n\023exportPublicKeyList\022" +
      "+.labs339.wallet.sign.ExportPublicKeyReq" +
      "uest\032,.labs339.wallet.sign.ExportPublicK" +
      "eyResponse\"\000\022h\n\rsignTxMessage\022).labs339." +
      "wallet.sign.SignTxMessageRequest\032*.labs3" +
      "39.wallet.sign.SignTxMessageResponse\"\000B." +
      "\n\031com.labs339.platform.signB\017WalletSignP" +
      "rotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_labs339_wallet_sign_SupportSignWayRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_labs339_wallet_sign_SupportSignWayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labs339_wallet_sign_SupportSignWayRequest_descriptor,
        new java.lang.String[] { "Chain", "Type", });
    internal_static_labs339_wallet_sign_SupportSignWayResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_labs339_wallet_sign_SupportSignWayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labs339_wallet_sign_SupportSignWayResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", "Support", });
    internal_static_labs339_wallet_sign_ExportPublicKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_labs339_wallet_sign_ExportPublicKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labs339_wallet_sign_ExportPublicKeyRequest_descriptor,
        new java.lang.String[] { "Wallet", "Chain", "Cursor", "Size", });
    internal_static_labs339_wallet_sign_ExportPublicKeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_labs339_wallet_sign_ExportPublicKeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labs339_wallet_sign_ExportPublicKeyResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", "PublicKey", });
    internal_static_labs339_wallet_sign_PublicKey_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_labs339_wallet_sign_PublicKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labs339_wallet_sign_PublicKey_descriptor,
        new java.lang.String[] { "Wallet", "Chain", "PublicKeyHex", "Index", });
    internal_static_labs339_wallet_sign_SignTxMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_labs339_wallet_sign_SignTxMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labs339_wallet_sign_SignTxMessageRequest_descriptor,
        new java.lang.String[] { "Wallet", "Chain", "Index", "UnSignMsg", });
    internal_static_labs339_wallet_sign_SignTxMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_labs339_wallet_sign_SignTxMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_labs339_wallet_sign_SignTxMessageResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
