// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet_sign.proto

// Protobuf Java Version: 3.25.1
package com.labs339.platform;

public interface ExportPublicKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:labs339.wallet.sign.ExportPublicKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wallet = 1;</code>
   * @return The wallet.
   */
  java.lang.String getWallet();
  /**
   * <code>string wallet = 1;</code>
   * @return The bytes for wallet.
   */
  com.google.protobuf.ByteString
      getWalletBytes();

  /**
   * <code>string chain = 2;</code>
   * @return The chain.
   */
  java.lang.String getChain();
  /**
   * <code>string chain = 2;</code>
   * @return The bytes for chain.
   */
  com.google.protobuf.ByteString
      getChainBytes();

  /**
   * <code>uint64 cursor = 3;</code>
   * @return The cursor.
   */
  long getCursor();

  /**
   * <code>uint64 size = 4;</code>
   * @return The size.
   */
  long getSize();
}
